Select Ceil(8.29) From Dual;
Select Ceil(-3.9) From Dual;
Select Ceil(17/3) From Dual;
Select Floor(-5.3) From Dual;
Select Floor(9.76) From Dual;
Select Floor(15/4) From Dual;
Select Sqrt(625) From Dual;
Select Sqrt(2) From Dual;
Select Abs(8.29) From Dual;
Select Abs(-3.14) From Dual;
Select Abs(-42) From Dual;
Select Sysdate As "Now" From Dual;
Select To_Char(Sysdate,'yyyy-mm-dd')As Date_format,To_Char(Sysdate, 'HH24:mi:ss')As Time_format From Dual;
Select Systimestamp From Dual;
Select Least('Apple','Banana','Cherry') As Smallest_String From Dual;
Select Greatest('Apple','Banana','Cherry') As Largest_String From Dual;
Select Ltrim('     Trim me') As Trimmed_String From Dual;
Select Rtrim('I LOve India     ') As Trimmed_String From Dual;
Select Rpad('Anumol VS','15','X') As Padded_Name From Dual;
Select Rpad('123','6','0') As Padded_No From Dual;
Select Reverse('U evol I') From Dual;
Select Case When 'racecar'=Reverse('racecar') Then 'Palindrome' Else 'Not Palindrome' End As Result From Dual;
Select Length('Oracle Datebase') From Dual;
Select 'Oracle'||' '||'SQL'||' '||'is'||' '||'Powerful'||' '||'and'||' '||'flexible' As Concatenated_String From Dual;
Select Concat('Anumol',' VS') From Dual;
Select Substr('India is my country',Instr('India is my country','is'),2) From Dual;
Select Substr('Anumol VS',2,3) From Dual;
Select Substr('Substring',1,3) From Dual;
Commit;
